EXCHANGE = "bybit"

SYMBOL = "BTC/USDT"

TIMEFRAME = "1d"

CANDLE_LIMIT = 200

# Application lifecycle mode: ONE_SHOT or LONG_RUNNING.
APPLICATION_MODE = "ONE_SHOT"
CANDLE_OPERATION_TIMEOUT_SECONDS = 60.0

# Public Bybit V5 live market-data settings (no credentials required).
BYBIT_WS_URL = "wss://stream.bybit.com/v5/public/linear"
LIVE_ORDER_BOOK_DEPTH = 50
LIVE_RECONNECT_INITIAL_DELAY = 1.0
LIVE_RECONNECT_MAX_DELAY = 30.0
LIVE_MESSAGE_TIMEOUT = 30.0

# Informational live order-flow runtime. This does not affect trading decisions.
LIVE_ORDER_FLOW_ENABLED = True
LIVE_ORDER_FLOW_SYMBOLS = ["BTCUSDT"]
LIVE_ORDER_FLOW_ANALYSIS_INTERVAL = 2.0
LIVE_ORDER_FLOW_TRADE_WINDOW = 60.0
LIVE_ORDER_FLOW_SNAPSHOT_HISTORY = 200
LIVE_READY_TIMEOUT_SECONDS = 3.0
LIVE_FIRST_ANALYSIS_TIMEOUT_SECONDS = 5.0
LIVE_SUMMARY_INTERVAL_SECONDS = 10.0
